version: 2

jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check Formatting
          command: |
              rustup component add rustfmt
              rustfmt --version
              cargo fmt --all -- --check --color=auto
      - run:
          name: Build all targets
          command: cargo build --workspace --all-targets
      - run:
          name: Build no_std targets
          command: |
              cargo build --manifest-path=src/gc-arena/Cargo.toml --no-default-features
              cargo build --manifest-path=src/gc-sequence/Cargo.toml --no-default-features
      - run:
          name: Run all tests
          command: cargo test --workspace
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
